server:
  port: 8080

spring:
  application:
    name: campus-canteen-content
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/campus_canteen_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

# Knife4j 配置
knife4j:
  enable: true
  production: false
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-search: true
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml
# OSS 配置
oss:
  accessKey: ${OSS_ACCESS_KEY:hmnsNF1WwJMUaDp00aVwjVaGN1dmettsLSvTgovj}
  secretKey: ${OSS_SECRET_KEY:hmnsNF1WwJMUaDp00aVwjVaGN1dmettsLSvTgovj}
  bucket: ${OSS_BUCKET:campus-canteen}
  domain: ${OSS_DOMAIN:https://t7th4rtp3.hn-bkt.clouddn.com}
